name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn' # Use Yarn caching for workspaces

      # Step 3: Install dependencies using Yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Step 4: Build all packages in the workspace
      - name: Build workspace
        run: yarn build

      # Optional: Cache Node.js dependencies
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/**/node_modules
          key: yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ matrix.node-version }}-
